### PR TITLE
make malachite-nz no_std ready

### PR DESCRIPTION
**Pull request by shekohex**
That's a followup #34

### CODE REVIEW

**Comment by mhogrefe** [comment]
Thank you! Are you planning on doing malachite-q and malachite-float as well? If not, I will.

**Comment by shekohex** [comment]
> Thank you! Are you planning on doing malachite-q and malachite-float as well? If not, I will.

Oh well, I may do it in my free time, but for now, I'm just using these two crates. Just saying it was easy doing it, but a bit of a chore work tbh lol. 

Anyway, thank you for your work and support for malachite.

**Comment by mhogrefe** [comment]
You're welcome! Okay, I'll do the last two crates myself.

**Comment by mhogrefe** [comment]
All of the crates are no_std now! Released as part of Malachite 0.4.5.

**Pull request merged**
